/* 시퀀스 삭제 */
/* 계정번호 시퀀스 삭제 */
DROP SEQUENCE SEQ_ACC_NUM;

/* 휴게소번호 시퀀스 삭제 */
DROP SEQUENCE SEQ_AREA_NUM;

/* 즐겨찾기번호 시퀀스 삭제 */
DROP SEQUENCE SEQ_FAV_NUM;

/* 주유소번호 시퀀스 삭제 */
DROP SEQUENCE SEQ_PET_NUM;

/* 리뷰번호 시퀀스 삭제 */
DROP SEQUENCE SEQ_REV_NUM;

/* 음식번호 시퀀스 삭제 */
DROP SEQUENCE SEQ_FOOD_NUM;

/* 문의사항번호 시퀀스 삭제 */
DROP SEQUENCE SEQ_INQ_NUM;

/* 공지사항번호 시퀀스 삭제 */
DROP SEQUENCE SEQ_NOT_NUM;

/* FAQ번호 시퀀스 삭제 */
DROP SEQUENCE SEQ_FAQ_NUM;


/* 테이블 삭제 */
/* 계정 테이블 삭제 */
DROP TABLE ACCOUNT
	CASCADE CONSTRAINTS;

/* 휴게소 테이블 삭제 */
DROP TABLE AREA
	CASCADE CONSTRAINTS;

/* 즐겨찾기 테이블 삭제 */
DROP TABLE FAVORITE
	CASCADE CONSTRAINTS;

/* 주유소 테이블 삭제 */
DROP TABLE PETROL
	CASCADE CONSTRAINTS;

/* 리뷰 테이블 삭제 */
DROP TABLE REVIEW
	CASCADE CONSTRAINTS;

/* 음식 테이블 삭제 */
DROP TABLE FOOD
	CASCADE CONSTRAINTS;

/* 편의시설 테이블 삭제 */
DROP TABLE FACILITY
	CASCADE CONSTRAINTS;

/* 문의사항 테이블 삭제 */
DROP TABLE INQUIRY
	CASCADE CONSTRAINTS;

/* 문의답변 테이블 삭제 */
DROP TABLE ANSWER
	CASCADE CONSTRAINTS;

/* 공지사항 테이블 삭제 */
DROP TABLE NOTICE
	CASCADE CONSTRAINTS;

/* FAQ 테이블 삭제 */
DROP TABLE FAQ
	CASCADE CONSTRAINTS;

	
/* 테이블 생성 */
/* 계정 테이블 생성 */
CREATE TABLE ACCOUNT (
    ACC_NUM NUMBER(10) NOT NULL, /* 계정번호 */
    NAME VARCHAR2(255) NOT NULL, /* 계정이름 */
    ADM_ID VARCHAR2(255), /* 관리자ID */
    USER_EMAIL VARCHAR2(255), /* 사용자이메일 */
    PASS VARCHAR2(255) NOT NULL, /* 계정비밀번호 */
    TEL VARCHAR2(255) NOT NULL, /* 계정전화번호 */
    INPUT_DATE DATE DEFAULT SYSDATE, /* 계정가입일 */
    WITHDRAW VARCHAR2(255) DEFAULT 'N', /* 계정탈퇴여부 */
    ROLLTYPE NUMBER(5) NOT NULL, /* 계정타입 */
    AUTH_CODE VARCHAR2(255) /* 인증번호 */
);

/* 휴게소 테이블 생성 */
CREATE TABLE AREA (
    AREA_NUM NUMBER(10) NOT NULL, /* 휴게소번호 */
    NAME VARCHAR2(255) NOT NULL, /* 휴게소이름 */
    ADDR VARCHAR2(255) NOT NULL, /* 휴게소주소 */
    TEL VARCHAR2(50), /* 휴게소전화전호 */
    ROUTE VARCHAR2(255), /* 휴게소노선 */
    OPERATION_TIME VARCHAR2(255) DEFAULT '00:00 - 23:59', /* 휴게소영업시간 */
    FEED VARCHAR2(10) DEFAULT 'X', /* 수유실 */
    SLEEP VARCHAR2(10) DEFAULT 'X', /* 수면실 */
    SHOWER VARCHAR2(10) DEFAULT 'X', /* 샤워실 */
    LAUNDRY VARCHAR2(10) DEFAULT 'X', /* 세탁실 */
    CLINIC VARCHAR2(10) DEFAULT 'X', /* 병원 */
    PHARMACY VARCHAR2(10) DEFAULT 'X', /* 약국 */
    SHELTER VARCHAR2(10) DEFAULT 'X', /* 쉼터 */
    SALON VARCHAR2(10) DEFAULT 'X', /* 이발소 */
    AGRICULTURAL VARCHAR2(10) DEFAULT 'X', /* 농산물판매장 */
    REPAIR VARCHAR2(10) DEFAULT 'X', /* 경정비소 */
    TRUCK VARCHAR2(10) DEFAULT 'X', /* 화물차라운지 */
    TEMP VARCHAR2(10), /* 추가시설 */
    LAT VARCHAR2(255)  NOT NULL, /* 휴게소위도 */
    LNG VARCHAR2(255)  NOT NULL /* 휴게소경도 */
);

/* 즐겨찾기 테이블 생성 */
CREATE TABLE FAVORITE (
    FAV_NUM NUMBER(10) NOT NULL, /* 즐겨찾기번호 */
    NAME VARCHAR2(255), /* 휴게소이름 */
    ACC_NUM NUMBER(10) NOT NULL, /* 계정번호 */
    AREA_NUM NUMBER(10) NOT NULL /* 휴게소번호 */
);

/* 주유소 테이블 생성 */
CREATE TABLE PETROL (
    PET_NUM NUMBER(10) NOT NULL, /* 주유소번호 */
    TEL VARCHAR2(50), /* 주유소전화번호 */
    GASOLINE VARCHAR2(255), /* 휘발유 */
    DIESEL VARCHAR2(255), /* 경유 */
    LPG VARCHAR2(255), /* LPG */
    ELECT VARCHAR2(255) DEFAULT 'X', /* 전기 */
    HYDRO VARCHAR2(255) DEFAULT 'X' /* 수소 */
);

/* 리뷰 테이블 생성 */
CREATE TABLE REVIEW (
    REV_NUM NUMBER(10) NOT NULL, /* 리뷰번호 */
    CONTENT VARCHAR2(4000) NOT NULL, /* 리뷰내용 */
    NAME VARCHAR2(255) NOT NULL, /* 리뷰작성자 */
    INPUT_DATE DATE DEFAULT SYSDATE, /* 리뷰작성일 */
    REPORT NUMBER(10) DEFAULT 0, /* 누적신고 */
    HIDDEN_TYPE VARCHAR2(255) DEFAULT 'N', /*리뷰숨김여부*/
    AREA_NUM NUMBER(10) NOT NULL, /* 휴게소번호 */
    ACC_NUM NUMBER(10) NOT NULL /* 계정번호 */
);

/* 음식 테이블 생성 */
CREATE TABLE FOOD (
    FOOD_NUM NUMBER(10) NOT NULL, /* 음식번호 */
    NAME VARCHAR2(255) NOT NULL, /* 음식이름 */
    IMAGE BLOB, /* 음식사진 */
    PRICE VARCHAR2(50), /* 음식가격 */
    AREA_NUM NUMBER(10) NOT NULL /* 휴게소번호 */
);

/* 문의사항 테이블 생성 */
CREATE TABLE INQUIRY (
    INQ_NUM NUMBER(10) NOT NULL, /* 문의사항번호 */
    TITLE VARCHAR2(500) NOT NULL, /* 문의사항제목 */
    CONTENT VARCHAR2(4000) NOT NULL, /* 문의사항내용 */
    NAME VARCHAR2(255) NOT NULL, /* 문의사항작성자 */
    INPUT_DATE DATE DEFAULT SYSDATE, /* 문의사항작성일 */
    STATUS_TYPE VARCHAR2(255) DEFAULT '대기', /* 문의사항상태(대기,답변완료) */
    ACC_NUM NUMBER(10) NOT NULL /* 계정번호 */
);

/* 문의답변 테이블 생성 */
CREATE TABLE ANSWER (
    INQ_NUM NUMBER(10) NOT NULL, /* 문의사항번호 */
    CONTENT VARCHAR2(4000), /* 답변내용 */
    NAME VARCHAR2(255), /* 답변작성자 */
    INPUT_DATE DATE DEFAULT SYSDATE /* 답변작성일 */
);

/* 공지사항 테이블 생성 */
CREATE TABLE NOTICE (
    NOT_NUM NUMBER(10) NOT NULL, /* 공지사항번호 */
    TITLE VARCHAR2(500) NOT NULL, /* 공지사항제목 */
    CONTENT VARCHAR2(4000) NOT NULL, /* 공지사항내용 */
    NAME VARCHAR2(255) NOT NULL, /* 공지사항작성자 */
    INPUT_DATE DATE DEFAULT SYSDATE, /* 공지사항작성일 */
    STATUS_TYPE VARCHAR2(255) DEFAULT '미공지', /* 공지사항상태(공지중,미공지) */
    ACC_NUM NUMBER(10) NOT NULL /* 계정번호 */
);

/* FAQ 테이블 생성 */
CREATE TABLE FAQ (
    FAQ_NUM NUMBER(10) NOT NULL, /* FAQ번호 */
    TITLE VARCHAR2(500) NOT NULL, /* FAQ제목 */
    CONTENT VARCHAR2(4000) NOT NULL, /* FAQ내용 */
    NAME VARCHAR2(255) NOT NULL, /* FAQ작성자 */
	INPUT_DATE DATE DEFAULT SYSDATE, /* FAQ작성일 */
    ACC_NUM NUMBER(10) NOT NULL /* 계정번호 */
);


/* 시퀀스 생성 */
/* 계정번호 시퀀스 생성 */
CREATE SEQUENCE SEQ_ACC_NUM
INCREMENT BY 1
START WITH 1
MAXVALUE 9999999999;

/* 즐겨찾기번호 시퀀스 생성 */
CREATE SEQUENCE SEQ_FAV_NUM
INCREMENT BY 1
START WITH 1
MAXVALUE 9999999999;


/* 주유소번호 시퀀스 생성 */
CREATE SEQUENCE SEQ_PET_NUM
INCREMENT BY 1
START WITH 1
MAXVALUE 9999999999;

/* 리뷰번호 시퀀스 생성 */
CREATE SEQUENCE SEQ_REV_NUM
INCREMENT BY 1
START WITH 1
MAXVALUE 9999999999;

/* 음식번호 시퀀스 생성 */
CREATE SEQUENCE SEQ_FOOD_NUM
INCREMENT BY 1
START WITH 1
MAXVALUE 9999999999;

/* 문의사항번호 시퀀스 생성 */
CREATE SEQUENCE SEQ_INQ_NUM
INCREMENT BY 1
START WITH 1
MAXVALUE 9999999999;

/* 공지사항번호 시퀀스 생성 */
CREATE SEQUENCE SEQ_NOT_NUM
INCREMENT BY 1
START WITH 1
MAXVALUE 9999999999;

/* FAQ번호 시퀀스 생성 */
CREATE SEQUENCE SEQ_FAQ_NUM
INCREMENT BY 1
START WITH 1
MAXVALUE 9999999999;


/* Primary Key 설정 */
/* 계정번호 PK 설정 */
ALTER TABLE ACCOUNT
ADD CONSTRAINT PK_ACCOUNT PRIMARY KEY (ACC_NUM);

/* 휴게소번호 PK 설정 */
ALTER TABLE AREA
ADD CONSTRAINT PK_AREA PRIMARY KEY (AREA_NUM);

/* 즐겨찾기번호 PK 설정 */
ALTER TABLE FAVORITE
ADD CONSTRAINT PK_FAVORITE PRIMARY KEY (FAV_NUM);

/* 주유소번호 PK 설정 */
ALTER TABLE PETROL
ADD CONSTRAINT PK_PETROL PRIMARY KEY (PET_NUM);

/* 리뷰번호 PK 설정 */
ALTER TABLE REVIEW
ADD CONSTRAINT PK_REVIEW PRIMARY KEY (REV_NUM);

/* 음식번호 PK 설정 */
ALTER TABLE FOOD
ADD CONSTRAINT PK_FOOD PRIMARY KEY (FOOD_NUM);

/* 문의사항번호 PK 설정 */
ALTER TABLE INQUIRY
ADD CONSTRAINT PK_INQUIRY PRIMARY KEY (INQ_NUM);

/* 공지사항번호 PK 설정 */
ALTER TABLE NOTICE
ADD CONSTRAINT PK_NOTICE PRIMARY KEY (NOT_NUM);

/* FAQ번호 PK 설정 */
ALTER TABLE FAQ
ADD CONSTRAINT PK_FAQ PRIMARY KEY (FAQ_NUM);


/* Foreign Key 설정 */
/* 즐겨찾기 테이블 계정번호 FK 설정 */
ALTER TABLE FAVORITE
ADD CONSTRAINT FK_ACCOUNT_TO_FAVORITE
FOREIGN KEY (ACC_NUM)
REFERENCES ACCOUNT (ACC_NUM);

/* 즐겨찾기 테이블 휴게소번호 FK 설정 */
ALTER TABLE FAVORITE
ADD CONSTRAINT FK_AREA_TO_FAVORITE
FOREIGN KEY (AREA_NUM)
REFERENCES AREA (AREA_NUM);

/* 주유소 테이블 휴게소번호 FK 설정 */
ALTER TABLE PETROL
ADD CONSTRAINT FK_AREA_TO_PETROL
FOREIGN KEY (AREA_NUM)
REFERENCES AREA (AREA_NUM);

/* 리뷰 테이블 계정번호 FK 설정 */
ALTER TABLE REVIEW
ADD CONSTRAINT FK_ACCOUNT_TO_REVIEW
FOREIGN KEY (ACC_NUM)
REFERENCES ACCOUNT (ACC_NUM);

/* 리뷰 테이블 휴게소번호 FK 설정 */
ALTER TABLE REVIEW
ADD CONSTRAINT FK_AREA_TO_REVIEW
FOREIGN KEY (AREA_NUM)
REFERENCES AREA (AREA_NUM);

/* 음식 테이블 휴게소번호 FK 설정 */
ALTER TABLE FOOD
ADD CONSTRAINT FK_AREA_TO_FOOD
FOREIGN KEY (AREA_NUM)
REFERENCES AREA (AREA_NUM);

/* 문의사항 테이블 계정번호 FK 설정 */
ALTER TABLE INQUIRY
ADD CONSTRAINT FK_ACCOUNT_TO_INQUIRY
FOREIGN KEY (ACC_NUM)
REFERENCES ACCOUNT (ACC_NUM);

/* 문의답변 테이블 문의사항번호 FK 설정 */
ALTER TABLE ANSWER
ADD CONSTRAINT FK_INQUIRY_TO_ANSWER
FOREIGN KEY (INQ_NUM)
REFERENCES INQUIRY (INQ_NUM);

/* 공지사항 테이블 계정번호 FK 설정 */
ALTER TABLE NOTICE
ADD CONSTRAINT FK_ACCOUNT_TO_NOTICE
FOREIGN KEY (ACC_NUM)
REFERENCES ACCOUNT (ACC_NUM);

/* FAQ 테이블 계정번호 FK 설정 */
ALTER TABLE FAQ
ADD CONSTRAINT FK_ACCOUNT_TO_FAQ
FOREIGN KEY (ACC_NUM)
REFERENCES ACCOUNT (ACC_NUM);
