ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE; -- 계정명 C## 안쓰고 만들 수 있게 하는 거, 만드시고 FALSE 하면 됩니다

CREATE USER highway IDENTIFIED BY tiger;

GRANT CONNECT TO highway;

GRANT RESOURCE TO highway;

GRANT CREATE TABLE TO highway;

GRANT CREATE VIEW TO highway;

GRANT CREATE SEQUENCE TO highway;

ALTER USER highway DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

commit;