/* 가데이터 생성 */
/* 계정 테이블 가데이터 생성 */
INSERT INTO ACCOUNT (ACC_NUM, NAME, ADM_ID, PASS, TEL, INPUT_DATE, ROLLTYPE)
VALUES	(SEQ_ACC_NUM.NEXTVAL, '김민경', 'admin01', 'admin1234', '010-2390-5309', '2025-05-07', '0');

INSERT INTO ACCOUNT (ACC_NUM, NAME, ADM_ID, PASS, TEL, INPUT_DATE, ROLLTYPE)
VALUES	(SEQ_ACC_NUM.NEXTVAL, '유명규', 'admin02', 'admin1234', '010-1290-4120', '2025-05-08', '0');

INSERT INTO ACCOUNT (ACC_NUM, NAME, ADM_ID, PASS, TEL, INPUT_DATE, ROLLTYPE)
VALUES	(SEQ_ACC_NUM.NEXTVAL, '이대웅', 'admin03', 'admin1234', '010-9193-8013', '2025-05-12', '0');

INSERT INTO ACCOUNT (ACC_NUM, NAME, USER_EMAIL, PASS, TEL, INPUT_DATE, ROLLTYPE)
VALUES	(SEQ_ACC_NUM.NEXTVAL, '홍길동', 'fatherbrother3@test.com', 'hong3', '010-1234-5678', '2021-12-12', '1');

INSERT INTO ACCOUNT (ACC_NUM, NAME, USER_EMAIL, PASS, TEL, INPUT_DATE, ROLLTYPE)
VALUES	(SEQ_ACC_NUM.NEXTVAL, '강태일', 'kang@sist.co.kr', 'kang96', '010-1114-6391', '2025-01-10', '1');

INSERT INTO ACCOUNT (ACC_NUM, NAME, USER_EMAIL, PASS, TEL, INPUT_DATE, ROLLTYPE)
VALUES	(SEQ_ACC_NUM.NEXTVAL, '이여진', 'yeojin@sist.co.kr', 'yeojin97', '010-8123-8700', '2025-05-05', '1');

INSERT INTO ACCOUNT (ACC_NUM, NAME, USER_EMAIL, PASS, TEL, INPUT_DATE, ROLLTYPE)
VALUES	(SEQ_ACC_NUM.NEXTVAL, '장태규', 'taegu321@sist.co.kr', 'taegu321', '010-3764-8070', '2025-05-07', '1');

INSERT INTO ACCOUNT (ACC_NUM, NAME, USER_EMAIL, PASS, TEL, INPUT_DATE, ROLLTYPE)
VALUES	(SEQ_ACC_NUM.NEXTVAL, '현지영', 'jiyeong@sist.co.kr', 'jiyeong', '010-2513-9568', '2025-05-08', '1');

INSERT INTO ACCOUNT (ACC_NUM, NAME, USER_EMAIL, PASS, TEL, INPUT_DATE, ROLLTYPE)
VALUES	(SEQ_ACC_NUM.NEXTVAL, '신민기', 'mingi@sist.co.k', 'ming90', '010-3123-2119', '2025-05-09', '1');

INSERT INTO ACCOUNT (ACC_NUM, NAME, USER_EMAIL, PASS, TEL, INPUT_DATE, ROLLTYPE)
VALUES	(SEQ_ACC_NUM.NEXTVAL, '유연수', 'yeonsoo@sist.co.kr', 'yeonsoo02', '010-8462-2597', '2025-05-10', '1');

INSERT INTO ACCOUNT (ACC_NUM, NAME, USER_EMAIL, PASS, TEL, INPUT_DATE, ROLLTYPE)
VALUES	(SEQ_ACC_NUM.NEXTVAL, '박선은', 'ksdsilver@sist.co.kr', 'ksdsilver01', '010-3648-1211', '2025-05-06', '1');

INSERT INTO ACCOUNT (ACC_NUM, NAME, USER_EMAIL, PASS, TEL, INPUT_DATE, ROLLTYPE)
VALUES	(SEQ_ACC_NUM.NEXTVAL, '심규민', 'deepmin@sist.co.kr', 'deepmin01', '010-5689-1209', '2025-05-08', '1');

INSERT INTO ACCOUNT (ACC_NUM, NAME, USER_EMAIL, PASS, TEL, INPUT_DATE, ROLLTYPE)
VALUES	(SEQ_ACC_NUM.NEXTVAL, '주현석', 'zoo@sist.co.kr', 'zoo99', '010-9812-2362', '2025-05-08', '1');

/* 휴게소 테이블 가데이터 생성 */
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000001'), '서울만남(부산)휴게소', '서울 서초구 원지동10-16', '02-578-3372', '경부선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', '37.459939', '127.042514');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000003'), '죽전(서울)휴게소', '경기 용인시 죽전2동866-2 ', '031-262-3168', '경부선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', '37.332583', '127.104397');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000005'), '기흥(부산)휴게소', '경기 용인시 기흥구공세로 173 기흥휴게소', '031-286-5001', '경부선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', '37.23509', '127.10519');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000007'), '안성(서울)휴게소', '경기 안성시 원곡면산하리(경부고속도로 372)', '031-611-5793', '경부선', 'O', 'O', 'O', 'O', 'O', 'X', 'O', 'X', 'O', 'X', 'O', '37.076443', '127.1318');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000009'), '안성(부산)휴게소', '경기 안성시 원곡면경부고속도로 365', '031-655-0531', '경부선', 'O', 'X', 'O', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', '37.013628', '127.145006');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000011'), '입장거봉포도(서울)휴게소', '충청남도 천안시 서북구 입장면연곡길 407', '041-588-7868', '경부선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'O', 'O', 'O', 'O', '36.942386', '127.192181');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000013'), '망향(부산)휴게소', '충남 천안시 성거읍요방리 121', '041-557-4000', '경부선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'O', 'O', 'X', '36.854892', '127.181208');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000015'), '천안삼거리(서울)휴게소', '충남 천안시 구성동171', '041-551-2480', '경부선', 'O', 'X', 'X', 'X', 'X', 'O', 'O', 'X', 'O', 'X', 'X', '36.787745', '127.173104');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000017'), '천안호두(부산)휴게소', '충남 천안시 수신면신풍리 447-3', '041-552-4560', '경부선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '36.730575', '127.264077');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000019'), '청주(서울)휴게소', '충북 청원군 옥산면 장남리284-16', '043-237-1700', '경부선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'X', 'X', 'O', '36.716001', '127.348115');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000021'), '옥산(부산)휴게소', '충북 청원군 옥산면오산리 589-15', '043-260-1053', '경부선', 'O', 'O', 'O', 'X', 'X', 'X', 'O', 'O', 'X', 'O', 'O', '36.656988', '127.370696');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000024'), '죽암(서울)휴게소', '충북 청원군 현도면죽전리 314', '043-260-8035', '경부선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'O', 'X', '36.496756', '127.430429');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000026'), '죽암(부산)휴게소', '충북 청주시 서원구 현도면 경부고속도로 289', '043-269-0850', '경부선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', '36.486933', '127.4296');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000028'), '신탄진(서울)휴게소', '대전시 대덕구 상서동236-1', '042-934-2442', '경부선', 'O', 'O', 'O', 'X', 'X', 'X', 'O', 'X', 'X', 'O', 'O', '36.426452', '127.418126');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000030'), '옥천(부산)휴게소', '충북 옥천군 옥천읍매화리 236-16', '043-731-8521', '경부선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'O', 'X', 'O', 'O', '36.297349', '127.595626');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000032'), '옥천(서울)휴게소', '충북 옥천군 옥천읍매화리(옥천동이로) 옥천동이로 242-34', '043-731-8097', '경부선', 'O', 'X', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'O', 'X', '36.2975', '127.59876');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000034'), '금강(부산)휴게소', '충북 옥천군 동이면조령리 568', '043-731-2233', '경부선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'O', 'X', '36.279109', '127.671587');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000036'), '황간(부산)휴게소', '충북 영동군 황간면회포리 103-2', '043-742-5805', '경부선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', '36.249', '127.852985');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000038'), '황간(서울)휴게소', '충북 영동군 황간면회포리 114', '043-742-7633', '경부선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', '36.249393', '127.85455');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000040'), '추풍령(부산)휴게소', '경북 김천시 봉산면광천리 691', '054-430-2000', '경부선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'X', 'O', 'O', '36.200481', '128.000838');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000042'), '추풍령(서울)휴게소', '경북 김천시 봉산면광천리 737-1', '054-439-3187', '경부선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'O', 'O', 'O', '36.200126', '128.0029');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000044'), '칠곡(부산)휴게소', '경북 칠곡군 왜관읍아곡리(경부고속도로) 159', '054-975-2277', '경부선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'O', 'X', 'O', '36.019492', '128.429257');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000046'), '칠곡(서울)휴게소', '경북 칠곡군 왜관읍아곡리 138', '054-975-1883', '경부선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'O', 'X', 'O', '36.012173', '128.430326');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000048'), '경산(서울)휴게소', '경북 경산시 진량면신상리 995-3', '053-852-5243', '경부선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'X', 'X', 'O', '35.878589', '128.809738');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000050'), '평사(부산)휴게소', '경북 경산시 진량읍경부고속도로105', '053-852-8651', '경부선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'X', 'X', 'O', '35.885738', '128.867177');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000052'), '건천(서울)휴게소', '경북 경주시 건천읍금척리 683-2', '054-751-7401', '경부선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', '35.831528', '129.109287');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000054'), '건천(부산)휴게소', '경북 경주시 건천읍방내리 14', '054-751-6890', '경부선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', '35.830287', '129.10946');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000055'), '경주(부산)휴게소', '경북 경주시 내남면 경부고속도로 59(월산리) 경주(부산)휴게소', '054-748-3195', '경부선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'X', 'X', 'O', '35.723932', '129.193338');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000057'), '언양(서울)휴게소', '울산광역시 울주군 언양읍반곡리 966-14', '052-263-6153', '경부선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'X', 'X', 'O', '35.597982', '129.141545');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000059'), '언양(부산)휴게소', '울산광역시 울주군 언양읍태기리 684-1', '055-383-6145', '경부선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '35.595511', '129.138917');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000062'), '양산(서울)휴게소', '경남 양산시 동면 내송리788번지', '055-384-0144', '경부선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '35.323178', '129.056383');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000063'), '진영(부산)휴게소', '경남 김해시 진영읍우동리(하계로96번길)', '055-334-8700', '남해선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'O', 'X', 'X', '35.278282', '128.71565');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000064'), '진영(순천)휴게소', '경남 김해시 진영읍우동리(하계로96번길) 68', '055-342-3959', '남해선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'O', 'X', '35.279663', '128.716021');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000071'), '문산(순천)휴게소', '경남 진주시 문산읍소문리 968-2', '055-761-2820', '남해선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '35.171422', '128.152339');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000073'), '사천(부산)휴게소', '경남 사천시 곤양면묵곡리(서삼로) 619번길', '055-854-3134', '남해선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'O', 'X', 'X', '35.073585', '128.010769');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000074'), '사천(순천)휴게소', '경남 사천시 곤양면묵곡리 산171-31', '055-854-3547', '남해선', 'O', 'X', 'O', 'X', 'X', 'X', 'O', 'X', 'O', 'X', 'X', '35.07468', '128.012612');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000077'), '섬진강(부산)휴게소', '전남 광양시 진월면신아리 1192-1', '061-772-7986', '남해선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'O', 'X', 'X', '34.984832', '127.770276');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000078'), '섬진강(순천)휴게소', '전남 광양시 진월면신아리 1192-1', '061-772-7993', '남해선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '34.985026', '127.769158');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000092'), '화성(서울)휴게소', '경기도 화성군 팔탄면덕천리 102-3', '031-353-8143', '서해안선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', '37.143508', '126.8809');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000093'), '화성(목포)휴게소', '경기도 화성군 팔탄면덕천리 102-1', '031-353-8140', '서해안선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', '37.144844', '126.879362');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000098'), '서산(목포)휴게소', '충청남도 서산시 해미면삼송리 119', '041-688-8814', '서해안선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '36.742902', '126.565625');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000100'), '서산(서울)휴게소', '충남 서산시 해미면삼송리(서해안고속도로) 242', '041-688-7714', '서해안선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'O', 'O', 'X', '36.733942', '126.565867');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000102'), '대천(서울)휴게소', '충남 보령시 주교면주교리 904-34', '041-931-6801', '서해안선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'O', 'O', 'X', '36.374231', '126.557651');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000103'), '대천(목포)휴게소', '충남 보령시 주교면주교리 933-5', '041-931-6901', '서해안선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'O', 'O', 'X', '36.373286', '126.556196');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000106'), '군산(서울)휴게소', '전북 군산시 나포면서해안고속도로 3182', '063-453-2818', '서해안선', 'O', 'O', 'O', 'O', 'X', 'O', 'O', 'X', 'O', 'X', 'O', '36.018829', '126.79706');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000108'), '군산(목포)휴게소', '전라북도 군산시 성산면산곡리 산1', '063-453-0402', '서해안선', 'O', 'X', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', '35.981049', '126.829206');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000110'), '고창고인돌(목포)휴게소', '전북 고창군 신림면벽송리 557-10', '063-561-6313', '서해안선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', '35.468235', '126.674104');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000112'), '고창고인돌(서울)휴게소', '전북 고창군 고창읍신월리(서해안고속도로)', '063-561-6323', '서해안선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', '35.462171', '126.672696');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000115'), '함평천지(서울)휴게소', '전라남도 함평군 손불면죽암리 29-1', '061-323-3641', '서해안선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'O', 'X', 'X', '35.130737', '126.481798');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000117'), '함평천지(목포)휴게소', '전남 함평군 함평읍 서해안고속도로 31', '061-323-3751', '서해안선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '35.069441', '126.478715');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000118'), '익산미륵사지(천안)휴게소', '전북 익산시 여산면호산리 24-1', '063-836-5168', '호남선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'X', 'X', 'O', '36.048553', '127.104473');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000119'), '익산미륵사지(순천)휴게소', '전북 익산시 여산면호남고속도로 191, 192', '063-836-5280', '호남선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'O', 'X', 'O', '36.048719', '127.103033');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000122'), '정읍녹두장군(천안)휴게소', '전북 정읍시 북면남산리 20-5', '063-532-2373', '호남선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', '35.600522', '126.86404');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000123'), '정읍녹두장군(순천)휴게소', '전북 정읍시 북면남산리 19-1', '063-532-0510', '호남선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', '35.601023', '126.862039');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000126'), '백양사(천안)휴게소', '전라남도 장성군 북일면 호남고속도로 108 (백양사휴게소(상행))박산리 158', '061-394-5177', '호남선', 'O', 'X', 'O', 'X', 'X', 'X', 'O', 'X', 'O', 'X', 'X', '35.393059', '126.807025');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000127'), '백양사(순천)휴게소', '전라남도 장성군 북이면 호남고속도로 107 (백양사휴게소(하))', '061-394-9990', '호남선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'O', 'X', 'X', '35.394365', '126.80574');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000130'), '곡성(천안)휴게소', '전남 곡성군 겸면가정리 347', '061-362-8300', '호남선', 'O', 'O', 'O', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '35.259215', '127.152509');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000131'), '곡성(순천)휴게소', '전남 곡성군 겸면가정리 산96-6', '061-363-2766', '호남선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '35.258559', '127.150882');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000134'), '주암(순천)휴게소', '전남 순천시 주암면고산리 252-2', '061-754-4980', '호남선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '35.076356', '127.264253');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000135'), '주암(천안)휴게소', '전남 순천시 주암면고산리 57-4', '061-754-2432', '호남선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '35.076802', '127.26553');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000138'), '순천(순천)휴게소', '전남 순천시 서면비월리 산169-2', '061-755-4982', '호남선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '35.009125', '127.444199');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000139'), '하남드림휴게소', '경기 하남시 중부고속도로 117', '031-791-4200', '중부선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '37.531023', '127.206502');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000141'), '이천쌀(하남)휴게소', '경기 이천시 신둔면서이천로853번길 346-129', '031-638-1117', '중부선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'O', 'X', 'X', '37.293444', '127.377767');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000144'), '이천(남이)휴게소', '경기 이천시 마장면목리 142', '031-637-0987', '중부선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', '37.265073', '127.403621');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000145'), '음성(하남)휴게소', '충북 음성군 삼성면양덕리 100-1', '043-878-6403', '중부선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'O', 'X', 'O', '37.021758', '127.483762');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000146'), '음성(남이)휴게소', '충북 음성군 삼성면용성리 산44', '043-878-6410', '중부선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '37.01967', '127.481522');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000149'), '오창(하남)휴게소', '충북 청원군 오창면화산리 396-10', '043-217-8303', '중부선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '36.756513', '127.481517');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000150'), '오창(남이)휴게소', '충북 청원군 오창면화산리 395-15', '043-217-1477', '중부선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', '36.758421', '127.482089');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000153'), '금산인삼랜드(대전)휴게소', '충남 금산군 군북면대암길 34-30', '041-754-9200', '통영대전선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', '36.154522', '127.497096');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000154'), '금산인삼랜드(통영)휴게소', '충남 금산군 군북면외부리 718', '041-751-2892', '통영대전선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', '36.153652', '127.496001');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000157'), '덕유산(대전)휴게소', '전라북도 무주군 안성면공진리 471', '063-353-4200', '통영대전선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', '35.816293', '127.645554');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000158'), '덕유산(통영)휴게소', '전라북도 장수군 계북면통영대전고속도로 147', '063-353-5100', '통영대전선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', '35.813367', '127.643616');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000165'), '산청(대전)휴게소', '경남 산청군 단성면방목리 산71-7', '055-973-5970', '통영대전선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'O', 'X', 'X', '35.333566', '127.938659');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000166'), '산청(통영)휴게소', '경남 산청군 단성면방목리 산68-7', '055-973-9036', '통영대전선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'O', 'X', 'X', '35.333707', '127.937512');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000169'), '충주(양평)휴게소', '충북 충주시 중앙탑면 중부내륙고속도록 230-1', '043-857-9339', '중부내륙선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'O', 'X', 'O', '37.022917', '127.838927');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000170'), '충주(창원)휴게소', '충북 충주시 가금면용전리 산 50-3', '043-857-9229', '중부내륙선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'O', 'X', 'O', '37.022352', '127.837551');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000173'), '선산(양평)휴게소', '경북 구미시 옥성면대원리 31-3', '054-482-6031', '중부내륙선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'O', 'X', 'X', '36.277695', '128.248999');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000174'), '선산(창원)휴게소', '경북 구미시 옥성면대원리 85-1', '054-482-6011', '중부내륙선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'O', 'X', 'X', '36.274604', '128.250736');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000177'), '영산(창원)휴게소', '경남 창녕군 영산면신제리 1471-1', '055-521-2978', '중부내륙선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'X', 'X', 'O', '35.429578', '128.496112');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000179'), '칠서(양평)휴게소', '경남 함안군 칠서면계내리 35', '055-587-9656', '중부내륙선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'O', 'O', 'O', '35.370958', '128.496632');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000181'), '강릉(강릉)휴게소', '강원도 강릉시 성산면보광리 산273', '033-648-8850', '영동선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '37.757987', '128.806307');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000182'), '강릉(인천)휴게소', '강원도 강릉시 성산면보광리 산4-2', '033-647-9970', '영동선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'O', 'X', 'X', '37.75933', '128.805602');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000186'), '평창(인천)휴게소', '강원 평창군 용평면이목정리', '033-333-6131', '영동선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'O', 'X', 'X', '37.610093', '128.463289');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000188'), '평창(강릉)휴게소', '강원도 평창군 용평면이목정리 778-2', '033-334-5100', '영동선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '37.60581', '128.453116');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000194'), '횡성(강릉)휴게소', '강원도 횡성군 안흥면 영동고속도로 154', '033-342-4231', '영동선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'O', 'X', 'X', '37.463308', '128.134391');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000195'), '횡성(인천)휴게소', '강원 횡성군 안흥면영동고속도로 153', '033-342-4200', '영동선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'O', 'X', 'X', '37.464746', '128.134925');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000199'), '문막(인천)휴게소', '강원 원주시 문막읍포진리', '033-734-7471', '영동선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'O', 'X', 'O', '37.29774', '127.817731');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000201'), '문막(강릉)휴게소', '강원 원주시 문막읍원문로 1234', '033-731-8481', '영동선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '37.335429', '127.857693');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000203'), '여주(강릉)휴게소', '경기 여주군 가남면본두리 687-1', '031-882-3120', '영동선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'O', 'X', 'O', '37.238548', '127.569035');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000204'), '여주(인천)휴게소', '경기도 여주시 가남읍화평길 116', '031-882-2900', '영동선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'O', 'X', 'X', '37.239578', '127.570116');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000207'), '용인(강릉)휴게소', '경기도 용인시 고림동9번지', '031-339-3663', '영동선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '37.24593', '127.242436');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000208'), '용인(인천)휴게소', '경기도 용인시 고림동89번지', '031-339-3660', '영동선', 'O', 'X', 'O', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '37.247924', '127.238279');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000211'), '춘천(부산)휴게소', '강원 춘천시 동내면 사암리산112-1', '033-264-0500', '중앙선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '37.812493', '127.766498');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000213'), '홍천강(춘천)휴게소', '강원도 홍천군 북방면소매곡리 294', '033-435-1201', '중앙선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', '37.712641', '127.827433');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000217'), '치악(부산)휴게소', '강원 원주시 신림면금창리(치악로)416 치악(부산)휴게소', '033-762-9234', '중앙선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'O', 'X', 'X', '37.253865', '128.049264');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000218'), '치악(춘천)휴게소', '강원도 원주시 신림면금창리 500-55', '033-762-8030', '중앙선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'O', 'X', 'X', '37.256212', '128.04863');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000221'), '단양팔경(춘천)휴게소', '충청북도 단양군 단성면하방리 56', '043-421-1671', '중앙선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'O', 'X', 'X', '36.942218', '128.323078');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000223'), '단양팔경(부산)휴게소', '충청북도 단양군 적성면기동리 산74-1', '043-423-5401', '중앙선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'O', 'X', 'X', '36.99489', '128.287624');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000225'), '안동(부산)휴게소', '경북 안동시 풍산읍계평리 산547-6', '054-853-4370', '중앙선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', '36.553396', '128.6427');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000226'), '안동(춘천)휴게소', '경북 안동시 풍산읍계평리 산128-2', '054-853-4061', '중앙선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', '36.553505', '128.644522');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000229'), '군위(부산)휴게소', '대구광역시 군위군 군위읍오곡리 산67-5', '054-383-6114', '중앙선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'O', '36.266428', '128.575347');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000230'), '군위(춘천)휴게소', '대구광역시 군위군 군위읍오곡리 산68-8', '054-383-7114', '중앙선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', '36.265744', '128.576516');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000233'), '동해(삼척)휴게소', '강원도 동해시 망상동산5-1', '033-534-6631', '동해선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '37.601565', '129.074237');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000236'), '장유(서부산)휴게소', '경남 김해시 장유면부곡리 53-1', '055-313-2610', '남해제2지선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', '35.212103', '128.794142');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000238'), '벌곡(대전)휴게소', '충남 논산시 벌곡면양산리124-1', '041-734-5250', '호남선의 지선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'X', 'X', 'O', '36.21053', '127.270254');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000240'), '벌곡(논산)휴게소', '충남 논산시 벌곡면호남지선고속도로25', '041-732-7694', '호남선의 지선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', '36.217785', '127.274017');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000243'), '현풍(대구)휴게소', '대구광역시 달성군 현풍면성하리 342', '053-615-0337', '중부내륙선의 지선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '35.702351', '128.437688');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000244'), '현풍(창원)휴게소', '대구 달성군 현풍면성하리 286', '053-614-2436', '중부내륙선의 지선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'O', 'X', 'X', '35.702309', '128.435982');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000249'), '동명(부산)휴게소', '경북 칠곡군 동명면가천리 120-2', '054-977-6921', '중앙선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', '36.006806', '128.546887');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000250'), '동명(춘천)휴게소', '경북 칠곡군 동명면 중앙고속도로 122', '054-977-6901', '중앙선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', '36.006181', '128.548814');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000253'), '홍성(서울)휴게소', '경기 이천시 부발읍아미리', '041-642-1172', '서해안선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '36.553084', '126.581503');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000254'), '홍성(목포)휴게소', '충남 홍성군 은하면금국리 292-3', '041-642-1151', '서해안선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '36.552828', '126.579955');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000261'), '서천(서울)휴게소', '충남 서천군 비인면성산리 22-4', '041-952-9700', '서해안선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', '36.131509', '126.627445');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000262'), '서천(목포)휴게소', '충남 서천군 비인면서해안고속도로169(성산리)', '041-952-5757', '서해안선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', '36.129844', '126.626738');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000267'), '구정(삼척)휴게소', '강원 강릉시 구정면제비리 888', '033-644-8345', '동해선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', '37.72247', '128.85147');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000268'), '문경(양평)휴게소', '경북 문경시 유곡동458', '054-554-1655', '중부내륙선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'X', 'O', 'O', '36.620477', '128.152145');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000269'), '함평나비(광주)휴게소', '전남 함평군 엄다면무안광주고속도로 12', '061-324-8840', '무안광주선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '35.037563', '126.511596');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000270'), '함평나비(무안)휴게소', '전남 함평군 엄다면화양리 1025-3번지', '061-324-8858', '무안광주선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '35.037959', '126.508996');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000273'), '문경(창원)휴게소', '경북 문경시 유곡동 중부내륙고속도로173460', '054-554-1610', '중부내륙선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'O', 'X', 'O', '36.620863', '128.150279');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000274'), '구정(속초)휴게소', '강원 강릉시 구정면동해고속도로 346', '033-644-4760', '동해선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', '37.72273', '128.853983');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000277'), '남성주참외(창원)휴게소', '경북 성주군 선남면명포리 880-5', '054-931-5741', '중부내륙선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'O', 'X', 'O', '35.868665', '128.316853');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000278'), '남성주참외(양평)휴게소', '경북 성주군 용암면본리 428', '054-933-7105', '중부내륙선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'O', 'X', 'O', '35.85787', '128.319554');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000280'), '화서(영덕)휴게소', '경북 상주시 화서면상용리 408', '054-531-1982', '서산영덕선', 'O', 'X', 'O', 'O', 'X', 'X', 'O', 'X', 'O', 'X', 'X', '36.444511', '127.922801');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000288'), '고성공룡나라(통영)휴게소', '경남 고성군 대가면송계리 447-7번지', '055-674-7028', '통영대전선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'X', 'X', 'O', '35.052082', '128.262946');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000289'), '고성공룡나라(대전)휴게소', '경남 고성군 대가면신전리 85번지', '055-674-0494', '통영대전선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '35.056324', '128.25234');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000292'), '덕평휴게소', '경기 이천시 마장면각평리 319', '031-645-0001', '영동선', 'O', 'X', 'X', 'X', 'X', 'O', 'O', 'X', 'O', 'X', 'X', '37.24133', '127.389428');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000295'), '괴산(양평)휴게소', '충북 괴산군 장연면오가리 293-2', '043-832-7966', '중부내륙선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'O', 'X', 'X', '36.831792', '127.959679');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000299'), '원주(부산)휴게소', '강원 원주시 호저면옥산리 211', '033-731-4291', '중앙선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', '37.435229', '127.929313');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000300'), '원주(춘천)휴게소', '강원 원주시 호저면옥산리 219-1', '033-731-8194', '중앙선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', '37.434678', '127.931495');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000301'), '옥계(속초)휴게소', '강원 강릉시 옥계면도직리 산2-2', '033-534-1700', '동해선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '37.61577', '129.059527');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000303'), '괴산(창원)휴게소', '충북 괴산군 장연면오가리 103번지', '043-832-6594', '중부내륙선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', '36.831323', '127.958253');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000306'), '김천(서울)휴게소', '경북 김천시 농소면신촌리 728-1', '054-433-1523', '경부선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'O', 'X', 'O', '36.130944', '128.16375');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000314'), '예산(대전)휴게소', '충남 예산군 신양면서계양리 662-28', '041-334-0094', '서산영덕선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'O', 'X', 'O', '36.623441', '126.84018');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000316'), '예산(당진)휴게소', '충남 예산군 신양면서계양리 672-3', '041-335-0020', '서산영덕선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'O', 'X', 'O', '36.619037', '126.84619');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000318'), '공주(대전)휴게소', '충남 공주시 장기면송선리 320-3', '041-854-6060', '서산영덕선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', '36.497236', '127.166632');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000320'), '부여백제(공주)휴게소', '충남 부여군 내산면율암리 149-5', '041-834-5600', '서천공주선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', '36.258669', '126.799831');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000321'), '부여백제(서천)휴게소', '충남 부여군 내산면율암리  134', '041-833-5400', '서천공주선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', '36.257748', '126.796921');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000324'), '공주(당진)휴게소', '충남 공주시 의당면청룡리 65-16', '041-854-0050', '서산영덕선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', '36.498179', '127.165274');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000331'), '안성맞춤(평택)휴게소', '경기 안성시 서운면신능리 51-16 외 23필지', '031-673-3822', '평택제천선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', '36.969702', '127.274757');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000333'), '안성맞춤(제천)휴게소', '경기 안성시 서운면신능리 51-11 외 29필지', '031-674-4406', '평택제천선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', '36.968311', '127.27416');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000341'), '행담도휴게소', '충남 당진군 신평면매산리 513', '041-358-0702', '서해안선', 'O', 'X', 'X', 'X', 'X', 'O', 'O', 'X', 'O', 'O', 'X', '36.944596', '126.807768');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000342'), '김천(부산)휴게소', '경북 김천시 농소면신촌리 730-2', '054-435-0211', '경부선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'O', 'X', 'O', '36.12927', '128.164892');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000344'), '함안(부산)휴게소', '경남 함안군 군북면유현리 산 993-6', '055-582-2191', '남해선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'O', 'X', 'O', '35.293779', '128.346804');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000347'), '진주(부산)휴게소', '경남 진주시 호탄동382 외 62필지', '055-759-3205', '남해선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '35.160064', '128.121951');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000348'), '함안(순천)휴게소', '경남 함안군 군북면유현리 산 993-1', '055-582-5470', '남해선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'O', 'X', 'X', '35.294139', '128.344495');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000350'), '서여주(양평)휴게소', '경기 여주시 세종대왕면중부내륙고속도로 272', '031-884-9714', '중부내륙선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '37.278893', '127.580067');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000351'), '서여주(창원)휴게소', '경기 여주시 세종대왕면중부내륙고속도로 271', '031-885-9760', '중부내륙선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '37.278948', '127.57867');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000355'), '이서(순천)휴게소', '서울 송파구 송파동185-5', '063-227-4114', '호남선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'X', 'X', 'O', '35.804013', '127.024278');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000358'), '이서(천안)휴게소', '서울 송파구 송파동185-5', '063-236-2592', '호남선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'O', 'X', 'O', '35.801984', '127.025328');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000360'), '오수(완주)휴게소', '전북 임실군 순천완주고속도로 74', '063-644-5115', '순천완주선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'X', 'X', 'O', '35.540312', '127.311318');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000361'), '오수(순천)휴게소', '전북 임실군 오수면오산리 675-18', '063-644-6116', '순천완주선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'O', 'X', 'O', '35.540749', '127.309624');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000364'), '황전(순천)휴게소', '전남 순천시 황전면선변리 560-7', '061-782-1135', '순천완주선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '35.148688', '127.454629');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000365'), '황전(완주)휴게소', '전남 순천시 황전면선변리 595-7', '061-782-1154', '순천완주선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '35.152685', '127.454595');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000371'), '구리(일산)휴게소', '경기 구리시 사노동170-13 구리고속도로휴게소', '031-529-3564', '수도권제1순환선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', '37.627981', '127.139087');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000396'), '성주(창원)휴게소', '경북 성주군 초전면용봉리 산129-48', '054-932-0800', '중부내륙선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'O', 'X', 'O', '36.00855', '128.260946');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000397'), '성주(양평)휴게소', '경북 성주군 초전면용봉리(중부내륙고속도로)', '054-933-0800', '중부내륙선', 'O', 'O', 'O', 'O', 'X', 'X', 'O', 'X', 'O', 'X', 'O', '36.010327', '128.260271');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000400'), '보성녹차(순천)휴게소', '전남 보성군 겸백면수남리 385-3', '070-4325-8808', '남해선(영암순천)', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '34.807645', '127.180953');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000401'), '보성녹차(영암)휴게소', '전남 보성군 미력면화방리 산 196-7', '070-4325-8801', '남해선(영암순천)', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '34.813993', '127.126007');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000404'), '옥천만남휴게소', '충북 옥천군 옥천읍중앙로 135', '043-732-0081', '경부선', 'X', 'O', 'O', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'O', '36.309081', '127.571338');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000409'), '마장휴게소', '경기 이천시 마장면목리 산 13-32', '031-630-0001', '중부선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', '37.264224', '127.406646');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000413'), '금왕(평택)휴게소', '충북 음성군 금왕읍용계리', '043-877-7000', '평택제천선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'O', 'X', 'X', '36.970286', '127.589609');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000414'), '금왕(제천)휴게소', '충북 음성군 금왕읍용계리 평택제천고속도로 70', '043-881-0001', '평택제천선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'O', 'X', 'X', '36.969184', '127.590581');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000419'), '천등산(제천)휴게소', '충북 충주시 산척면평택제천고속도로 106', '043-844-2991', '평택제천선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'O', 'X', 'X', '37.061732', '127.939496');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000420'), '천등산(평택)휴게소', '충북 충주시 산척면평택제천고속도로 109', '043-844-2930', '평택제천선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'O', 'X', 'X', '37.076657', '127.989022');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000440'), '외동(포항)휴게소', '경북 경주시 외동읍상석길 58-70', '054-745-0631', '울산포항선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '35.672948', '129.287791');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000441'), '외동(부산)휴게소', '경상북도 경주시 외동읍 내외로 577-189상석길 58-74', '054-745-0637', '울산포항선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '35.672748', '129.286187');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000495'), '의성(청주)휴게소', '경북 의성군 안계면새못안길 45-49', '054-862-9076', '서산영덕선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '36.410784', '128.444761');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000496'), '의성(영덕)휴게소', '경북 의성군 안계면새못안길 45-47', '054-862-9252', '서산영덕선', 'O', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', 'X', 'X', '36.409625', '128.447588');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000503'), '청송(청주)휴게소', '경북 청송군 파천면중평병부길 203-92', '054-873-5911', '서산영덕선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', '36.456696', '129.011593');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000504'), '청송(영덕)휴게소', '경북 청송군 파천면중평병부길 203-115', '054-873-9102', '서산영덕선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', '36.45568', '129.01376');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000509'), '홍천(서울)휴게소', '강원특별자치도 홍천군 화촌면서울양양고속도로 83', '033-436-9000', '서울양양선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', '37.916366', '128.287173');
INSERT INTO AREA (AREA_NUM, NAME, ADDR, TEL, ROUTE, FEED, SLEEP, SHOWER, LAUNDRY, CLINIC, PHARMACY, SHELTER, SALON, AGRICULTURAL, REPAIR, TRUCK, LAT, LNG)
VALUES(TO_NUMBER('000510'), '홍천(양양)휴게소', '강원특별자치도 홍천군 화촌면서울양양고속도로 84', '033-436-3000', '서울양양선', 'O', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'O', 'X', 'X', '35.269655', '129.003226');


/* 즐겨찾기 테이블 가데이터 생성 */
/* 1 계정당 20개씩 데이터 */
-- ACC_NUM = 4
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=112), 4, 112);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=32), 4, 32);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=5), 4, 5);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=26), 4, 26);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=54), 4, 54);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=419), 4, 419);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=364), 4, 364);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=213), 4, 213);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=50), 4, 50);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=145), 4, 145);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=404), 4, 404);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=28), 4, 28);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=397), 4, 397);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=92), 4, 92);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=316), 4, 316);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=496), 4, 496);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=93), 4, 93);
-- ACC_NUM = 5
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=9), 5, 9);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=413), 5, 413);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=274), 5, 274);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=261), 5, 261);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=158), 5, 158);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=268), 5, 268);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=28), 5, 28);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=269), 5, 269);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=496), 5, 496);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=182), 5, 182);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=15), 5, 15);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=46), 5, 46);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=48), 5, 48);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=170), 5, 170);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=509), 5, 509);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=126), 5, 126);
-- ACC_NUM = 6
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL, 
(SELECT NAME FROM AREA WHERE AREA_NUM=141), 6, 141);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=273), 6, 273);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=371), 6, 371);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=509), 6, 509);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=278), 6, 278);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=150), 6, 150);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=341), 6, 341);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=204), 6, 204);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=110), 6, 110);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=194), 6, 194);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=34), 6, 34);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=73), 6, 73);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=238), 6, 238);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=130), 6, 130);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=331), 6, 331);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=441), 6, 441);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=230), 6, 230);
-- ACC_NUM = 7
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=46), 7, 46);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=254), 7, 254);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=170), 7, 170);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=270), 7, 270);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=115), 7, 115);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=253), 7, 253);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=211), 7, 211);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=409), 7, 409);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=50), 7, 50);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=3), 7, 3);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=413), 7, 413);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=117), 7, 117);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=358), 7, 358);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=169), 7, 169);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=414), 7, 414);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=350), 7, 350);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=441), 7, 441);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=44), 7, 44);
-- ACC_NUM = 8
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=233), 8, 233);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=158), 8, 158);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=218), 8, 218);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=134), 8, 134);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=174), 8, 174);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=117), 8, 117);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=173), 8, 173);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=153), 8, 153);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=244), 8, 244);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=318), 8, 318);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=130), 8, 130);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=299), 8, 299);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=413), 8, 413);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=103), 8, 103);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=123), 8, 123);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=77), 8, 77);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=324), 8, 324);
-- ACC_NUM = 9
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=106), 9, 106);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=52), 9, 52);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=510), 9, 510);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=324), 9, 324);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=71), 9, 71);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=509), 9, 509);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=344), 9, 344);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=211), 9, 211);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=365), 9, 365);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=321), 9, 321);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=280), 9, 280);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=504), 9, 504);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=158), 9, 158);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=249), 9, 249);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=110), 9, 110);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=165), 9, 165);
-- ACC_NUM = 10
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=30), 10, 30);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=46), 10, 46);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=106), 10, 106);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=365), 10, 365);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=131), 10, 131);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=141), 10, 141);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=199), 10, 199);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=204), 10, 204);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=344), 10, 344);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=400), 10, 400);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=166), 10, 166);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=110), 10, 110);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=413), 10, 413);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=19), 10, 19);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=157), 10, 157);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=350), 10, 350);
-- ACC_NUM = 11
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=355), 11, 355);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=509), 11, 509);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=358), 11, 358);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=9), 11, 9);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=314), 11, 314);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=123), 11, 123);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=169), 11, 169);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=278), 11, 278);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=1), 11, 1);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=150), 11, 150);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=92), 11, 92);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=48), 11, 48);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=98), 11, 98);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=103), 11, 103);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=52), 11, 52);
-- ACC_NUM = 12
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=348), 12, 348);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=324), 12, 324);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=401), 12, 401);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=441), 12, 441);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=145), 12, 145);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=223), 12, 223);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=347), 12, 347);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=203), 12, 203);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=496), 12, 496);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=117), 12, 117);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=46), 12, 46);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=179), 12, 179);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=267), 12, 267);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=221), 12, 221);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=32), 12, 32);
-- ACC_NUM = 13
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=182), 13, 182);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=360), 13, 360);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=149), 13, 149);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=154), 13, 154);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=21), 13, 21);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=11), 13, 11);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=268), 13, 268);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=250), 13, 250);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=396), 13, 396);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=126), 13, 126);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=261), 13, 261);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=207), 13, 207);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=316), 13, 316);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=122), 13, 122);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=420), 13, 420);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=320), 13, 320);
INSERT INTO FAVORITE (FAV_NUM, NAME, ACC_NUM, AREA_NUM)
VALUES (SEQ_FAV_NUM.NEXTVAL,
(SELECT NAME FROM AREA WHERE AREA_NUM=333), 13, 333);


/* 문의사항 테이블 가데이터 생성 */
/* 1 계정당 1~2개씩 데이터 */
-- ACC_NUM = 6
INSERT INTO INQUIRY (INQ_NUM, TITLE, CONTENT, NAME, ACC_NUM)
VALUES (SEQ_INQ_NUM.NEXTVAL, '로그인 오류', '로그인이 되지 않아요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=6), 6);
INSERT INTO INQUIRY (INQ_NUM, TITLE, CONTENT, NAME, STATUS_TYPE, ACC_NUM)
VALUES (SEQ_INQ_NUM.NEXTVAL, '회원탈퇴', '회원탈퇴는 어디서 하나요?',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=6), '답변완료', 6);
-- ACC_NUM = 7
INSERT INTO INQUIRY (INQ_NUM, TITLE, CONTENT, NAME, ACC_NUM)
VALUES (SEQ_INQ_NUM.NEXTVAL, '전화번호 수정', '전화번호를 바꾸고 싶어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=7), 7);
INSERT INTO INQUIRY (INQ_NUM, TITLE, CONTENT, NAME, STATUS_TYPE, ACC_NUM)
VALUES (SEQ_INQ_NUM.NEXTVAL, '아이디 찾기', '아이디를 잊어버렸습니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=7), '답변완료', 7);
-- ACC_NUM = 8
INSERT INTO INQUIRY (INQ_NUM, TITLE, CONTENT, NAME, ACC_NUM)
VALUES (SEQ_INQ_NUM.NEXTVAL, '이벤트 일정', '다음 이벤트는 언제인가요?',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=8), 8);
INSERT INTO INQUIRY (INQ_NUM, TITLE, CONTENT, NAME, STATUS_TYPE, ACC_NUM)
VALUES (SEQ_INQ_NUM.NEXTVAL, '비밀번호 변경', '비밀번호는 어디서 변경하나요?',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=8), '답변완료', 8);
-- ACC_NUM = 9
INSERT INTO INQUIRY (INQ_NUM, TITLE, CONTENT, NAME, ACC_NUM)
VALUES (SEQ_INQ_NUM.NEXTVAL, '휴면 계정 복구', '휴면 계정은 어떻게 복구하나요?',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=9), 9);
INSERT INTO INQUIRY (INQ_NUM, TITLE, CONTENT, NAME, STATUS_TYPE, ACC_NUM)
VALUES (SEQ_INQ_NUM.NEXTVAL, '이벤트 일정', '다음 이벤트는 언제인가요?',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=9), '답변완료', 9);
-- ACC_NUM = 10
INSERT INTO INQUIRY (INQ_NUM, TITLE, CONTENT, NAME, STATUS_TYPE, ACC_NUM)
VALUES (SEQ_INQ_NUM.NEXTVAL, '전화번호 수정', '전화번호를 바꾸고 싶어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=10), '답변완료', 10);
-- ACC_NUM = 11
INSERT INTO INQUIRY (INQ_NUM, TITLE, CONTENT, NAME, STATUS_TYPE, ACC_NUM)
VALUES (SEQ_INQ_NUM.NEXTVAL, '탈퇴 후 재가입', '탈퇴 후 재가입이 가능한가요?',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=11), '답변완료', 11);
-- ACC_NUM = 12
-- ACC_NUM = 13
INSERT INTO INQUIRY (INQ_NUM, TITLE, CONTENT, NAME, STATUS_TYPE, ACC_NUM)
VALUES (SEQ_INQ_NUM.NEXTVAL, '닉네임 변경', '닉네임은 이름 말고 바꿀 수 있나요?',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=13), '답변완료', 13);


/* 문의답변 테이블 가데이터 생성 */
INSERT INTO ANSWER (INQ_NUM, CONTENT, NAME)
VALUES (2, '마이페이지에서 회원 탈퇴가 가능합니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=2));
INSERT INTO ANSWER (INQ_NUM, CONTENT, NAME)
VALUES (4, '가입 시 이메일로 전송된 아이디를 확인해주세요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=2));
INSERT INTO ANSWER (INQ_NUM, CONTENT, NAME)
VALUES (6, '마이페이지에서 비밀번호를 변경하실 수 있습니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=2));
INSERT INTO ANSWER (INQ_NUM, CONTENT, NAME)
VALUES (8, '다음 이벤트 일정은 예정되지 않았습니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=2));
INSERT INTO ANSWER (INQ_NUM, CONTENT, NAME)
VALUES (9, '마이페이지에서 전화번호를 변경하실 수 있습니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=2));
INSERT INTO ANSWER (INQ_NUM, CONTENT, NAME)
VALUES (10, '탈퇴 후 30일 이후 재가입 가능합니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=2));
INSERT INTO ANSWER (INQ_NUM, CONTENT, NAME)
VALUES (11, '닉네임은 별도로 없으며 실명제로 운영하고 있습니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=2));

/* 공지사항 테이블 가데이터 생성 */
INSERT INTO NOTICE (NOT_NUM, TITLE, CONTENT, NAME, INPUT_DATE, ACC_NUM)
VALUES (SEQ_NOT_NUM.NEXTVAL, '홈페이지 운영시간 안내', '모두쉼 홈페이지 운영시간은 오전 9:00-오후 6:00 입니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=3),
'2025-05-05', 3);

INSERT INTO NOTICE (NOT_NUM, TITLE, CONTENT, NAME, STATUS_TYPE, ACC_NUM)
VALUES (SEQ_NOT_NUM.NEXTVAL, '모두쉼 홈페이지 서비스 론칭 이벤트 ', '친구와 지인에게 홈페이지를 공유해주세요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=3),
'미공지', 3);

/* FAQ 테이블 가데이터 생성 */
INSERT INTO FAQ (FAQ_NUM, TITLE, CONTENT, NAME, ACC_NUM)
VALUES (SEQ_FAQ_NUM.NEXTVAL, '전기/수소차 충전소 정보 제공 안내', '전기 충전소는 공공데이터 연계로 3~4분 정도 지연이 있으며, 갱신 주기는 5분입니다. 수소 충전소는 정보 확인 시 지연 시간 없이 제공하고 있습니다. *한국환경공단 전기자동차 충전소 정보 등 활용',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=3),  3);

INSERT INTO FAQ (FAQ_NUM, TITLE, CONTENT, NAME, ACC_NUM)
VALUES (SEQ_FAQ_NUM.NEXTVAL, '통행료와 관련된 내용은 어디에 문의하나요?', '한국도로공사 홈페이지에서 조회 및 검색이 가능합니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=3),  3);

INSERT INTO FAQ (FAQ_NUM, TITLE, CONTENT, NAME, ACC_NUM)
VALUES (SEQ_FAQ_NUM.NEXTVAL, '주유소 정보는 실시간인가요?', '모두쉼 홈페이지는 한국도로공사가 수집한 데이터를 매일 업데이트하여 교통정보를 제공하기 위해 노력하고 있습니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=3),  3);

INSERT INTO FAQ (FAQ_NUM, TITLE, CONTENT, NAME, ACC_NUM)
VALUES (SEQ_FAQ_NUM.NEXTVAL, '내비게이션 기능이 있나요?', '모두쉼 홈페이지는 내비게이션 기능을 제공하고 있지 않습니다. 경로 검색 시 Tmap과 카카오 내비를 연계하여 내비게이션 서비스를 이용하실 수 있습니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=3),  3);

INSERT INTO FAQ (FAQ_NUM, TITLE, CONTENT, NAME, ACC_NUM)
VALUES (SEQ_FAQ_NUM.NEXTVAL, '개인정보를 수집하나요?', '모두쉼 홈페이지는 이용자의 개인정보를 별도로 수집·저장하거나 외부로 일체 제공하지 않습니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=3),  3);

commit;
