/* 리뷰 테이블 가데이터 생성 */
/* 1 계정당 5개씩 데이터 */
-- ACC_NUM = 4
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '시설이 청결하고 편안했어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=4), 141, 4);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '음식이 정말 기대 이상이었어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=4), 74, 4);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '날씨 좋은 날 들르기 딱입니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=4), 318, 4);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '화장실이 넓고 냄새도 없어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=4), 127, 4);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '가족 단위 방문에 적합해요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=4), 249, 4);
-- ACC_NUM = 5
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '작지만 알찬 구성의 휴게소였습니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=5), 300, 5);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '조용해서 잠깐 눈 붙이기 좋았어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=5), 166, 5);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '화장실에 손 세정제 비치되어 있어서 만족.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=5), 344, 5);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '매점 물가가 생각보다 괜찮아요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=5), 244, 5);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '잘 쉬고 기분 좋게 출발할 수 있었어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=5), 103, 5);
-- ACC_NUM = 6
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '음식이 정말 기대 이상이었어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=6), 320, 6);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '시설이 청결하고 편안했어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=6), 351, 6);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '날씨 좋은 날 들르기 딱입니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=6), 36, 6);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '가족 단위 방문에 적합해요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=6), 413, 6);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '잘 쉬고 기분 좋게 출발할 수 있었어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=6), 303, 6);
-- ACC_NUM = 7
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '조용해서 잠깐 눈 붙이기 좋았어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=7), 203, 7);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '작지만 알찬 구성의 휴게소였습니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=7), 236, 7);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '화장실에 손 세정제 비치되어 있어서 만족.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=7), 269, 7);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '매점 물가가 생각보다 괜찮아요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=7), 11, 7);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '음식이 정말 기대 이상이었어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=7), 173, 7);
-- ACC_NUM = 8
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '시설이 청결하고 편안했어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=8), 127, 8);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '화장실이 넓고 냄새도 없어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=8), 371, 8);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '날씨 좋은 날 들르기 딱입니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=8), 158, 8);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '가족 단위 방문에 적합해요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=8), 50, 8);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '작지만 알찬 구성의 휴게소였습니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=8), 211, 8);
-- ACC_NUM = 9
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '조용해서 잠깐 눈 붙이기 좋았어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=9), 401, 9);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '화장실에 손 세정제 비치되어 있어서 만족.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=9), 149, 9);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '날씨 좋은 날 들르기 딱입니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=9), 146, 9);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '매점 물가가 생각보다 괜찮아요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=9), 144, 9);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '잘 쉬고 기분 좋게 출발할 수 있었어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=9), 300, 9);
-- ACC_NUM = 10
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '현지 음식이 정말 맛있고 푸짐했어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=10), 1, 10);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '쉬기 딱 좋은 분위기의 휴게소였습니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=10), 126, 10);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '기념품이 다양해서 구경하는 재미가 있었어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=10), 289, 10);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '도로 진입이 편하고 깔끔해서 좋았어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=10), 34, 10);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '가족 단위로 오기 좋은 장소입니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=10), 504, 10);
-- ACC_NUM = 11
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '공기가 맑고 산책로가 인상적이었습니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=11), 213, 11);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '편의시설이 잘 갖춰져 있었어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=11), 360, 11);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '야경이 멋진 휴게소였습니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=11), 169, 11);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '화장실이 많고 쾌적했어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=11), 179, 11);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '반려동물 동반이 가능한 점이 좋았어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=11), 78, 11);
-- ACC_NUM = 12
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '정체 중 들렸는데 정말 힐링됐어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=12), 318, 12);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '아이들이 놀기 좋은 공간이 있었어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=12), 38, 12);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '전체적으로 쾌적하고 조용했어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=12), 221, 12);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '간식 코너가 다양해서 좋았어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=12), 270, 12);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '드라이브 중 꼭 들러야 할 곳 같아요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=12), 420, 12);
-- ACC_NUM = 13
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '뷰가 너무 좋아서 사진도 많이 찍었어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=13), 306, 13);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '깨끗하고 정돈된 인상이었어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=13), 218, 13);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '주차 구역이 넓어서 이용하기 편했어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=13), 268, 13);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '피곤할 때 쉬기에 최적의 장소입니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=13), 102, 13);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '자연경관이 멋진 곳이에요!',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=13), 240, 13);



commit;