-- 강릉(강릉) → 181
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 181);

-- 강릉(인천) → 182
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 182);

-- 건천(부산) → 54
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 54);

-- 건천(서울) → 52
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 52);

-- 경산(서울) → 48
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 48);

-- 경주(부산) → 55
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 55);

-- 고성공룡나라(대전) → 289
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 289);

-- 고성공룡나라(통영) → 288
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 288);

-- 고창고인돌(목포) → 110
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 110);

-- 고창고인돌(서울) → 112
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 112);

-- 곡성(순천) → 131
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 131);

-- 곡성(천안) → 130
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 130);

-- 공주(당진) → 324
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 324);

-- 공주(대전) → 318
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 318);

-- 괴산(양평) → 295
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 295);

-- 괴산(창원) → 303
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 303);

-- 구리(일산) → 371
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 371);

-- 구정(삼척) → 267
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 267);

-- 구정(속초) → 274
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 274);

-- 군산(목포) → 108
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 108);

-- 군산(서울) → 106
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 106);

-- 군위(부산) → 229
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 229);

-- 군위(춘천) → 230
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 230);

-- 금강(부산) → 34
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 34);

-- 금산인삼랜드(대전) → 153
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 153);

-- 금산인삼랜드(통영) → 154
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 154);

-- 금왕(제천) → 414
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 414);

-- 금왕(평택) → 413
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 413);

-- 기흥(부산) → 5
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 5);

-- 김천(부산) → 342
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 342);

-- 김천(서울) → 306
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 306);

-- 남성주참외(양평) → 278
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 278);

-- 남성주참외(창원) → 277
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 277);

-- 단양팔경(부산) → 223
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 223);

-- 단양팔경(춘천) → 221
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 221);

-- 대천(목포) → 103
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 103);

-- 대천(서울) → 102
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 102);

-- 덕유산(대전) → 157
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 157);

-- 덕유산(통영) → 158
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 158);

-- 덕평 → 292
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 292);

-- 동명(부산) → 249
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 249);

-- 동명(춘천) → 250
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 250);

-- 동해(삼척) → 233
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 233);

-- 마장 → 409
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 409);

-- 망향(부산) → 13
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 13);

-- 문경(양평) → 268
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 268);

-- 문경(창원) → 273
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 273);

-- 문막(강릉) → 201
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 201);

-- 문막(인천) → 199
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 199);

-- 문산(순천) → 71
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 71);

-- 백양사(순천) → 127
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 127);

-- 백양사(천안) → 126
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 126);

-- 벌곡(논산) → 240
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 240);

-- 벌곡(대전) → 238
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 238);

-- 보성녹차(순천) → 400
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 400);

-- 보성녹차(영암) → 401
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 401);

-- 부여백제(공주) → 320
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 320);

-- 부여백제(서천) → 321
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 321);

-- 사천(부산) → 73
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 73);

-- 사천(순천) → 74
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 74);

-- 산청(대전) → 165
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 165);

-- 산청(통영) → 166
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 166);

-- 서산(목포) → 98
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 98);

-- 서산(서울) → 100
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 100);

-- 서여주(양평) → 350
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 350);

-- 서여주(창원) → 351
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 351);

-- 서울만남(부산) → 1
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 1);

-- 서천(목포) → 262
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 262);

-- 서천(서울) → 261
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 261);

-- 선산(양평) → 173
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 173);

-- 선산(창원) → 174
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 174);

-- 섬진강(부산) → 77
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 77);

-- 섬진강(순천) → 78
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 78);

-- 성주(양평) → 397
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 397);

-- 성주(창원) → 396
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 396);

-- 순천(순천) → 138
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 138);

-- 신탄진(서울) → 28
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 28);

-- 안동(부산) → 225
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 225);

-- 안동(춘천) → 226
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 226);

-- 안성(부산) → 9
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 9);

-- 안성(서울) → 7
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 7);

-- 안성맞춤(제천) → 333
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 333);

-- 안성맞춤(평택) → 331
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 331);

-- 양산(서울) → 62
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 62);

-- 언양(서울) → 57
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 57);

-- 여주(강릉) → 203
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 203);

-- 여주(인천) → 204
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 204);

-- 영산(창원) → 177
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 177);

-- 예산(당진) → 316
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 316);

-- 예산(대전) → 314
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 314);

-- 오수(순천) → 361
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 361);

-- 오수(완주) → 360
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 360);

-- 오창(남이) → 150
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 150);

-- 오창(하남) → 149
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 149);

-- 옥계(속초) → 301
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 301);

-- 옥산(부산) → 21
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 21);

-- 옥천(부산) → 30
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 30);

-- 옥천(서울) → 32
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 32);

-- 옥천만남 → 404
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 404);

-- 외동(부산) → 441
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 441);

-- 외동(포항) → 440
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 440);

-- 용인(강릉) → 207
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 207);

-- 용인(인천) → 208
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 208);

-- 원주(부산) → 299
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 299);

-- 원주(춘천) → 300
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 300);

-- 음성(남이) → 146
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 146);

-- 음성(하남) → 145
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 145);

-- 의성(영덕) → 496
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 496);

-- 의성(청주) → 495
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 495);

-- 이서(순천) → 355
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 355);

-- 이서(천안) → 358
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 358);

-- 이천(남이) → 144
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 144);

-- 입장거봉포도(서울) → 11
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 11);

-- 장유(서부산) → 236
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 236);

-- 정읍녹두장군(순천) → 123
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 123);

-- 정읍녹두장군(천안) → 122
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 122);

-- 주암(순천) → 134
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 134);

-- 주암(천안) → 135
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 135);

-- 죽암(부산) → 26
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 26);

-- 죽암(서울) → 24
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 24);

-- 죽전(서울) → 3
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 3);

-- 진영(부산) → 63
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 63);

-- 진영(순천) → 64
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 64);

-- 진주(부산) → 347
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 347);

-- 천등산(제천) → 419
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 419);

-- 천등산(평택) → 420
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 420);

-- 천안삼거리(서울) → 15
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 15);

-- 천안호두(부산) → 17
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 17);

-- 청송(영덕) → 504
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 504);

-- 청송(청주) → 503
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 503);

-- 청주(서울) → 19
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 19);

-- 추풍령(부산) → 40
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 40);

-- 추풍령(서울) → 42
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 42);

-- 춘천(부산) → 211
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 211);

-- 충주(양평) → 169
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 169);

-- 충주(창원) → 170
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 170);

-- 치악(부산) → 217
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 217);

-- 치악(춘천) → 218
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 218);

-- 칠곡(부산) → 44
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 44);

-- 칠곡(서울) → 46
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 46);

-- 칠서(양평) → 179
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 179);

-- 평사(부산) → 50
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 50);

-- 평창(강릉) → 188
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 188);

-- 평창(인천) → 186
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 186);

-- 하남드림 → 139
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 139);

-- 함안(부산) → 344
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 344);

-- 함안(순천) → 348
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 348);

-- 함평나비(광주) → 269
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 269);

-- 함평나비(무안) → 270
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 270);

-- 함평천지(목포) → 117
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 117);

-- 함평천지(서울) → 115
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 115);

-- 행담도 → 341
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 341);

-- 현풍(대구) → 243
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 243);

-- 현풍(창원) → 244
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 244);

-- 홍성(목포) → 254
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 254);

-- 홍성(서울) → 253
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 253);

-- 홍천(서울) → 509
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 509);

-- 홍천(양양) → 510
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 510);

-- 홍천강(춘천) → 213
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 213);

-- 화서(영덕) → 280
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 280);

-- 화성(목포) → 93
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 93);

-- 화성(서울) → 92
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 92);

-- 황간(부산) → 36
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 36);

-- 황간(서울) → 38
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 38);

-- 황전(순천) → 364
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 364);

-- 황전(완주) → 365
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 365);

-- 횡성(강릉) → 194
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 194);

-- 횡성(인천) → 195
INSERT INTO PETROL (PET_NUM, GASOLINE, DIESEL, LPG, ELECT, HYDRO, AREA_NUM)
VALUES(SEQ_PET_NUM.NEXTVAL, '1,500원', '1,400원', 'X', 'O', 'X', 195);

commit;