/* 리뷰 테이블 가데이터 생성 */
/* 1 계정당 5개씩 데이터 */
-- ACC_NUM = 4
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '시설이 청결하고 편안했어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=4), 33, 4);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '음식이 정말 기대 이상이었어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=4), 204, 4);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '날씨 좋은 날 들르기 딱입니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=4), 14, 4);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '화장실이 넓고 냄새도 없어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=4), 160, 4);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '가족 단위 방문에 적합해요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=4), 97, 4);
-- ACC_NUM = 5
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '작지만 알찬 구성의 휴게소였습니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=5), 48, 5);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '조용해서 잠깐 눈 붙이기 좋았어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=5), 57, 5);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '화장실에 손 세정제 비치되어 있어서 만족.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=5), 80, 5);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '매점 물가가 생각보다 괜찮아요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=5), 136, 5);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '잘 쉬고 기분 좋게 출발할 수 있었어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=5), 144, 5);
-- ACC_NUM = 6
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '음식이 정말 기대 이상이었어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=6), 21, 6);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '시설이 청결하고 편안했어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=6), 28, 6);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '날씨 좋은 날 들르기 딱입니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=6), 146, 6);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '가족 단위 방문에 적합해요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=6), 37, 6);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '잘 쉬고 기분 좋게 출발할 수 있었어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=6), 141, 6);
-- ACC_NUM = 7
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '조용해서 잠깐 눈 붙이기 좋았어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=7), 198, 7);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '작지만 알찬 구성의 휴게소였습니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=7), 126, 7);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '화장실에 손 세정제 비치되어 있어서 만족.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=7), 83, 7);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '매점 물가가 생각보다 괜찮아요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=7), 151, 7);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '음식이 정말 기대 이상이었어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=7), 197, 7);
-- ACC_NUM = 8
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '시설이 청결하고 편안했어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=8), 18, 8);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '화장실이 넓고 냄새도 없어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=8), 147, 8);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '날씨 좋은 날 들르기 딱입니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=8), 48, 8);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '가족 단위 방문에 적합해요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=8), 132, 8);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '작지만 알찬 구성의 휴게소였습니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=8), 145, 8);
-- ACC_NUM = 9
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '조용해서 잠깐 눈 붙이기 좋았어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=9), 170, 9);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '화장실에 손 세정제 비치되어 있어서 만족.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=9), 73, 9);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '날씨 좋은 날 들르기 딱입니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=9), 186, 9);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '매점 물가가 생각보다 괜찮아요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=9), 13, 9);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '잘 쉬고 기분 좋게 출발할 수 있었어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=9), 50, 9);
-- ACC_NUM = 10
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '현지 음식이 정말 맛있고 푸짐했어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=10), 122, 10);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '쉬기 딱 좋은 분위기의 휴게소였습니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=10), 25, 10);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '기념품이 다양해서 구경하는 재미가 있었어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=10), 152, 10);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '도로 진입이 편하고 깔끔해서 좋았어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=10), 15, 10);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '가족 단위로 오기 좋은 장소입니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=10), 47, 10);
-- ACC_NUM = 11
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '공기가 맑고 산책로가 인상적이었습니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=11), 173, 11);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '편의시설이 잘 갖춰져 있었어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=11), 155, 11);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '야경이 멋진 휴게소였습니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=11), 204, 11);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '화장실이 많고 쾌적했어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=11), 145, 11);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '반려동물 동반이 가능한 점이 좋았어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=11), 64, 11);
-- ACC_NUM = 12
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '정체 중 들렸는데 정말 힐링됐어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=12), 80, 12);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '아이들이 놀기 좋은 공간이 있었어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=12), 43, 12);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '전체적으로 쾌적하고 조용했어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=12), 22, 12);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '간식 코너가 다양해서 좋았어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=12), 136, 12);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '드라이브 중 꼭 들러야 할 곳 같아요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=12), 109, 12);
-- ACC_NUM = 13
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '뷰가 너무 좋아서 사진도 많이 찍었어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=13), 113, 13);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '깨끗하고 정돈된 인상이었어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=13), 93, 13);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '주차 구역이 넓어서 이용하기 편했어요.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=13), 67, 13);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '피곤할 때 쉬기에 최적의 장소입니다.',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=13), 56, 13);
INSERT INTO REVIEW (REV_NUM, CONTENT, NAME, AREA_NUM, ACC_NUM)
VALUES (SEQ_REV_NUM.NEXTVAL, '자연경관이 멋진 곳이에요!',
(SELECT NAME FROM ACCOUNT WHERE ACC_NUM=13), 114, 13);